name: duitwise
description: A gamified financial literacy application for kids.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.6.0
  http: ^1.2.0
  video_player: ^2.11.1
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png