// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLlQ9tFjx75TRL0ITic4dLgj6xwTbTZvA',
    appId: '1:285999310317:web:243b5444153aa73b01f3e4',
    messagingSenderId: '285999310317',
    projectId: 'duitwise',
    authDomain: 'duitwise.firebaseapp.com',
    storageBucket: 'duitwise.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHHZOTO0Zv12Ioaoi4cweiEluM5k871g0',
    appId: '1:285999310317:android:b7033508e230236001f3e4',
    messagingSenderId: '285999310317',
    projectId: 'duitwise',
    storageBucket: 'duitwise.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCemJV7bSSEV7zVxqVRwBIG9gaIoVAdUAU',
    appId: '1:285999310317:ios:8ad35a7b9463177601f3e4',
    messagingSenderId: '285999310317',
    projectId: 'duitwise',
    storageBucket: 'duitwise.firebasestorage.app',
    iosBundleId: 'com.example.duitwise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCemJV7bSSEV7zVxqVRwBIG9gaIoVAdUAU',
    appId: '1:285999310317:ios:8ad35a7b9463177601f3e4',
    messagingSenderId: '285999310317',
    projectId: 'duitwise',
    storageBucket: 'duitwise.firebasestorage.app',
    iosBundleId: 'com.example.duitwise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLlQ9tFjx75TRL0ITic4dLgj6xwTbTZvA',
    appId: '1:285999310317:web:b2bd57224affb8e901f3e4',
    messagingSenderId: '285999310317',
    projectId: 'duitwise',
    authDomain: 'duitwise.firebaseapp.com',
    storageBucket: 'duitwise.firebasestorage.app',
  );
}
